name: 'quickrun-demo'

services:
  task-service:
    image: qinxuwei/quickrun-demo-task-service:latest
    container_name: task-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://task-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    restart: unless-stopped
    depends_on:
      task-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m

  order-service:
    image: qinxuwei/quickrun-demo-order-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://orders-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=quickrun-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - TASK_SERVICE_URL=http://task-service:8081
    restart: unless-stopped
    depends_on:
      orders-db:
        condition: service_healthy
      quickrun-rabbitmq:
        condition: service_healthy
      task-service:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m