name: task Service

on:
  push:
    paths:
      - task-service/**
    branches:
      - 'master'
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./task-service

    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v5  # 拉取代码

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QUICKRUN_USERNAME }}
          password: ${{ secrets.QUICKRUN_TOKEN }}
